--CREATE TABLE User_Model(
--    id SERIAL PRIMARY KEY,
--    name VARCHAR (50),
--    username VARCHAR (50)
--    user_age INTEGER,
--    user_date TIMESTAMP,
--    courses_direction VARCHAR(50),
--    level_actual VARCHAR (30),
--    level_courses VARCHAR (30),
--    courses_duration VARCHAR (100),
--    courses_language VARCHAR (50)
--);